### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by jonbretman**
- [ ] Make tests run again
- [x] Ensure that this failure case results in a failed build

### CODE REVIEW

**Comment by jonnyreeves** [comment]
`ts_test/util.ts` is the culprit, deleting that file causes the tests to pass.

**Comment by jonny-improbable** [comment]
@jonbretman #64 adds a check to ensure that at least one test runs (and fails the build if that's not the case) - this should prevent this kind of failure from happening again.

**Comment by jonbretman** [comment]
@jonnyreeves do you understand this test failure? I'm not sure how to fix it....

https://travis-ci.org/improbable-eng/ts-protoc-gen/builds/376766536#L851

```
  1) service/grpc-web should generate valid javascript sources:
     evalmachine.<anonymous>:90
exports.SimpleServiceClient = SimpleServiceClient;
                                                 ^
SyntaxError: Unexpected end of input
      at createScript (vm.js:80:10)
      at Object.runInContext (vm.js:119:10)
      at Context.<anonymous> (build/test/ts_test/src/service/grpcweb.js:56:14)
```

**Comment by jonbretman** [comment]
@jonnyreeves any chance you'll have time to look at this? I've given it another pass but really don't understand the error.

**Comment by jonny-improbable** [comment]
@jonbretman just pushed some new commits which pass locally for me 🤞

**Comment by jonny-improbable** [comment]
🎉 master is green again!

**Comment by jonbretman** [comment]
@jonny-improbable it doesn't look like Travis is even running builds for master though? [This page](https://travis-ci.org/improbable-eng/ts-protoc-gen/branches) suggests it last ran 11 months ago.

**Pull request merged**
