### PR TITLE
Migrate from deprecated babel to babel-cli package

### PR DESCRIPTION
**Pull request by easyCZ**
* Addresses a deprecation warning during `npm install`
* Adds `package-lock`

### CODE REVIEW

**Comment by jonnyreeves** [comment]
Lgtm

**Comment by easyCZ** [comment]
@jonnyreeves Thanks. Could you please merge? I don't have permission

**Comment by jonnyreeves** [comment]
Neither do I 😂😂😂

**Comment by easyCZ** [comment]
@MarcusLongmuir could you please merge?

**Pull request merged**
