### PR TITLE
Add support for proto3 optional presence

### PR DESCRIPTION
**Pull request by awbraunstein**
## Changes

Add implementation for proto3 optional fields with presence tracking. Spec: https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md

Fixes: https://github.com/improbable-eng/ts-protoc-gen/issues/263

Additionally, this change:
- Improves tests for the proto2 scalar messages
- Explicitly calls `.buffer` on the serialized message before passing into `Buffer.from` to handle a weird typescript issue.

## Verification

Tested via unit tests and visual inspection of generated files.

### CODE REVIEW

**Comment by awbraunstein** [comment]
@MarcusLongmuir would appreciate a review on this. Thanks.

**Comment by MarcusLongmuir** [comment]
Thanks for raising this @awbraunstein. @moadz is currently reviewing this. Will try to cut a release for this soon after it lands.

**Review by moadz — APPROVED** [review]
LGTM, thank you for completing this!

**Comment by stof** [comment]
@MarcusLongmuir any chance to make a release containing this feature ?

protoc 3.15.0 ships with it as a non-experimental feature.

**Pull request merged**
