### PR TITLE
Bumped to v0.13.1-pre

### PR DESCRIPTION
**Pull request by MarcusLongmuir**
## Changes

* Bumped to v0.13.1-pre

### CODE REVIEW

**Review by moadz — APPROVED** [review]

**Review by moadz — APPROVED** [review]

**Review by petemounce — APPROVED** [review]

**Comment by jonnyreeves** [comment]
Has this been approved?

**Comment by MarcusLongmuir** [comment]
Want to give it a 👍 too, Jonny?

**Pull request merged**
