### PR TITLE
fix: Expose `message` on ClientStream Service stubs

### PR DESCRIPTION
**Pull request by George-Payne**
## Changes

- Add optional callback to clientStream to return response.
- Callback is called after `end` event
- Amend types with overload for optional metadata

## Verification

Tested generated code:
   - both metadata and callback
   - only callback
   - only metadata
   - neither

fixes: #208

### CODE REVIEW

**Comment by watjurk** [comment]
Hi, is there a chance of this PR getting merged ?
Thanks !

**Review by moadz — APPROVED** [review]
This LGTM @MarcusLongmuir can you take another quick look for change rationale

**Comment by edaniels** [comment]
Can we get this merged in?

**Comment by jucrouzet** [comment]
Hi @MarcusLongmuir @moadz ,

Is there a chance to have this merged or any update that can fix this problem ?

Regards,

**Comment by MarcusLongmuir** [comment]
I pushed changes to this to fix a callback ordering issue and added integration tests. Thanks for the contribution 👍

**Review by MarcusLongmuir — APPROVED** [review]

**Comment by jucrouzet** [comment]
Thanks a lot

**Pull request merged**
