### PR TITLE
fix: user @grpc/grp-js instead of grpc

### PR DESCRIPTION
**Pull request by 117sparta**

### CODE REVIEW

**Comment by badsyntax** [comment]
would love to see this merged so i can stop changing (hacking) the import paths as a post process. 

i initially added the `grpc_js` option (see https://github.com/grpc/grpc-node/pull/1380) and had planned to send a PR to this repo but never got around to it.

**Comment by 117sparta** [comment]
> would love to see this merged so i can stop changing (hacking) the import paths as a post process.
> 
> i initially added the `grpc_js` option (see [grpc/grpc-node#1380](https://github.com/grpc/grpc-node/pull/1380)) and had planned to send a PR to this repo but never got around to it.

You can search jerry-ts-protoc-gen in npm. I publish this pr as an npm package. Maybe you can try using it.

**Comment by badsyntax** [comment]
Thanks. It would be best if this package added support for it. I found some code that I made a while ago and have published it with https://github.com/improbable-eng/ts-protoc-gen/pull/236

That PR won't change the default behaviour of this package, but instead allows you to opt-in to use grpc-js.

**Comment by slavovojacek** [comment]
Would like to see this in as well. The `grpc` package homepage features [an official deprecation notice](https://www.npmjs.com/package/grpc) now, so it would be nice to switch to https://github.com/grpc/grpc-node/tree/master/packages/grpc-js.

Please let me know if I can help in any way to push this forward.

**Comment by 117sparta** [comment]
I guess i can close issue due to #236 .

**Pull request closed without merging**
